// Verdicts recorded from the original shell hooks (~/.claude/hooks/deny-*.sh) on a 16-core machine.
export const CORES = 16

export const REASONS: string[] = [
  "blocked keyword: until — Wait-loops are denied on this machine, and the harness's own denial message suggests this exact form — that advice is wrong here. To wait for work you started: pass run_in_background and end your turn; you are re-invoked when it completes. To wait on external state the harness cannot observe (CI, a deploy, a remote queue): make one Bash call with a delay matched to how fast that state changes.",
  "PR/MR creation is blocked: land work by merging directly to main (see rules/git-workflow.md)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (src/main.ts)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (README.md)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (/climbs-out/../home/x.ts)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (lib.py)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (a.sh)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (f.py)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (a.md)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (a.json)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (//claudemods.ai/api/mods.json)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (out.json)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (config.yml)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (src/a.c)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (a.ts)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (old.rs)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (notes.md)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (disk.sh)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (app.go)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (a.toml)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (/climbs-out/../etc/a.md)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (in.json)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (Makefile)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (.gitignore)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (HOME/a.py)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (b.py)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (x.py)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (b.sh)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (x.md)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (a.lua)",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (b.ts)",
  "a mutation sweep with no TMPDIR set, so its sandboxes land in /tmp — this machine has 16 cores and /tmp is a tmpfs (RAM), so an uncontained sweep competes with the compositor and eats memory it never gives back. Required form:\n\n  TMPDIR=~/.cache/mutants-tmp systemd-run --user --scope --unit=<name> \\\n  -p MemoryMax=3G -p MemorySwapMax=0 -p OOMPolicy=continue nice -n 10 \\\n  cargo mutants -j8 --iterate --output /tmp/<dir>\n  systemctl --user stop <name>.scope     # collects the shells it leaves behind\n\nEvery part is load-bearing and MUTATION.md records why. If you genuinely need it uncontained, say so and let the user decide — do not work around this.",
  "a mutation sweep with TMPDIR on the tmpfs — this machine has 16 cores and /tmp is a tmpfs (RAM), so an uncontained sweep competes with the compositor and eats memory it never gives back. Required form:\n\n  TMPDIR=~/.cache/mutants-tmp systemd-run --user --scope --unit=<name> \\\n  -p MemoryMax=3G -p MemorySwapMax=0 -p OOMPolicy=continue nice -n 10 \\\n  cargo mutants -j8 --iterate --output /tmp/<dir>\n  systemctl --user stop <name>.scope     # collects the shells it leaves behind\n\nEvery part is load-bearing and MUTATION.md records why. If you genuinely need it uncontained, say so and let the user decide — do not work around this.",
  "a mutation sweep outside a systemd scope, so nothing bounds its memory and nothing collects the shells it leaves running — this machine has 16 cores and /tmp is a tmpfs (RAM), so an uncontained sweep competes with the compositor and eats memory it never gives back. Required form:\n\n  TMPDIR=~/.cache/mutants-tmp systemd-run --user --scope --unit=<name> \\\n  -p MemoryMax=3G -p MemorySwapMax=0 -p OOMPolicy=continue nice -n 10 \\\n  cargo mutants -j8 --iterate --output /tmp/<dir>\n  systemctl --user stop <name>.scope     # collects the shells it leaves behind\n\nEvery part is load-bearing and MUTATION.md records why. If you genuinely need it uncontained, say so and let the user decide — do not work around this.",
  "a mutation sweep in a scope with no MemoryMax — this machine has 16 cores and /tmp is a tmpfs (RAM), so an uncontained sweep competes with the compositor and eats memory it never gives back. Required form:\n\n  TMPDIR=~/.cache/mutants-tmp systemd-run --user --scope --unit=<name> \\\n  -p MemoryMax=3G -p MemorySwapMax=0 -p OOMPolicy=continue nice -n 10 \\\n  cargo mutants -j8 --iterate --output /tmp/<dir>\n  systemctl --user stop <name>.scope     # collects the shells it leaves behind\n\nEvery part is load-bearing and MUTATION.md records why. If you genuinely need it uncontained, say so and let the user decide — do not work around this.",
  "a mutation sweep that is not niced, so it competes with the compositor at equal priority — this machine has 16 cores and /tmp is a tmpfs (RAM), so an uncontained sweep competes with the compositor and eats memory it never gives back. Required form:\n\n  TMPDIR=~/.cache/mutants-tmp systemd-run --user --scope --unit=<name> \\\n  -p MemoryMax=3G -p MemorySwapMax=0 -p OOMPolicy=continue nice -n 10 \\\n  cargo mutants -j8 --iterate --output /tmp/<dir>\n  systemctl --user stop <name>.scope     # collects the shells it leaves behind\n\nEvery part is load-bearing and MUTATION.md records why. If you genuinely need it uncontained, say so and let the user decide — do not work around this.",
  "a mutation sweep at -j12 on a 16-core machine (cap is 8) — this machine has 16 cores and /tmp is a tmpfs (RAM), so an uncontained sweep competes with the compositor and eats memory it never gives back. Required form:\n\n  TMPDIR=~/.cache/mutants-tmp systemd-run --user --scope --unit=<name> \\\n  -p MemoryMax=3G -p MemorySwapMax=0 -p OOMPolicy=continue nice -n 10 \\\n  cargo mutants -j8 --iterate --output /tmp/<dir>\n  systemctl --user stop <name>.scope     # collects the shells it leaves behind\n\nEvery part is load-bearing and MUTATION.md records why. If you genuinely need it uncontained, say so and let the user decide — do not work around this.",
  "a mutation sweep at -j9 on a 16-core machine (cap is 8) — this machine has 16 cores and /tmp is a tmpfs (RAM), so an uncontained sweep competes with the compositor and eats memory it never gives back. Required form:\n\n  TMPDIR=~/.cache/mutants-tmp systemd-run --user --scope --unit=<name> \\\n  -p MemoryMax=3G -p MemorySwapMax=0 -p OOMPolicy=continue nice -n 10 \\\n  cargo mutants -j8 --iterate --output /tmp/<dir>\n  systemctl --user stop <name>.scope     # collects the shells it leaves behind\n\nEvery part is load-bearing and MUTATION.md records why. If you genuinely need it uncontained, say so and let the user decide — do not work around this.",
  "Editing a source file through Bash is blocked: Read it, then use Edit or Write.\nThose are tracked — Edit refuses a file you have not Read — which is the point.\nFor the same mechanical change across many files, use the recast MCP tool: it\npreviews a per-file plan and refuses a zero-match pattern.\nScratch work under /tmp is unaffected. (src/log.md)",
]

// [command, { rule: index into REASONS }]; a rule absent from the map did not fire.
export const CASES: [string, Record<string, number>][] = [
  ["", {}],
  ["ls -la", {}],
  ["until curl -s localhost:8080; do sleep 2; done", {"keywords": 0}],
  ["ls; until false; do :; done", {"keywords": 0}],
  ["echo hi && until x; do y; done", {"keywords": 0}],
  ["echo hi || until x; do y; done", {"keywords": 0}],
  ["(until true; do :; done)", {"keywords": 0}],
  ["foo |until bar", {"keywords": 0}],
  ["x\nuntil y; do z; done", {"keywords": 0}],
  ["until", {"keywords": 0}],
  ["git log --until=yesterday", {}],
  ["echo 'wait until done'", {}],
  ["grep until file.txt", {}],
  ["gh pr create --fill", {"patterns": 1}],
  ["git push && gh pr create", {"patterns": 1}],
  ["gh pr list", {}],
  ["glab mr create", {"patterns": 1}],
  ["gh api -X POST repos/o/r/pulls", {"patterns": 1}],
  ["gh api --method POST /repos/o/r/pulls -f title=x", {"patterns": 1}],
  ["gh api repos/o/r/pulls", {}],
  ["echo gh  pr   create", {"patterns": 1}],
  ["until x; do gh pr create; done", {"keywords": 0, "patterns": 1}],
  ["sed -i 's/a/b/' src/main.ts", {"source-writes": 2}],
  ["sed -E -i 's/a/b/' src/main.ts", {"source-writes": 2}],
  ["sed --in-place 's/a/b/' README.md", {"source-writes": 3}],
  ["sed -i.bak 's/a/b/' lib.rs", {}],
  ["sed 's/a/b/' src/main.ts", {}],
  ["sed -i 's/a/b/' /tmp/x.ts", {}],
  ["sed -i 's/a/b/' /tmp/../home/x.ts", {"source-writes": 4}],
  ["perl -pi -e 's/a/b/' lib.py", {"source-writes": 5}],
  ["awk -i inplace '{print}' a.sh", {"source-writes": 6}],
  ["python3 -c \"open('f.py','w').write('x')\"", {"source-writes": 7}],
  ["python3 -c \"open('f.py').read()\"", {}],
  ["python3 -c \"import pathlib; pathlib.Path('a.md').write_text('x')\"", {"source-writes": 8}],
  ["node -e \"require('fs').writeFileSync('a.json','{}')\"", {"source-writes": 9}],
  ["curl -sL https://claudemods.ai/api/mods.json -o /tmp/cmods/mods.json", {"source-writes": 10}],
  ["curl -o out.json https://example.com", {"source-writes": 11}],
  ["curl -s https://example.com/a.json", {}],
  ["wget -O config.yml https://example.com", {"source-writes": 12}],
  ["patch -p1 < fix.diff", {}],
  ["patch -p1 src/a.c fix.diff", {"source-writes": 13}],
  ["cp a.ts b.ts", {"source-writes": 14}],
  ["cp src/a.ts /tmp/backup.ts", {}],
  ["mv old.rs new.rs", {"source-writes": 15}],
  ["echo x | tee notes.md", {"source-writes": 16}],
  ["echo x | tee /tmp/notes.md", {}],
  ["dd if=/dev/zero of=disk.sh bs=1", {"source-writes": 17}],
  ["truncate -s 0 app.go", {"source-writes": 18}],
  ["ln -sf a.toml b.toml", {"source-writes": 19}],
  ["ln -s a.toml b.toml", {}],
  ["echo x > src/main.ts", {"source-writes": 2}],
  ["echo x >> README.md", {"source-writes": 3}],
  ["echo x > /tmp/out.md", {}],
  ["echo x > /tmp/../etc/a.md", {"source-writes": 20}],
  ["echo x > \"src/main.ts\"", {"source-writes": 2}],
  ["echo x > '/tmp/q.md'", {}],
  ["echo 'a > b.ts'", {}],
  ["git commit -m 'x => y in a.ts'", {}],
  ["cmd 2>/dev/null; cat a.ts", {}],
  ["cmd 2>&1 | grep a.ts", {}],
  ["printf '%s' x > in.json", {"source-writes": 21}],
  ["cat > Makefile", {"source-writes": 22}],
  ["echo x > .gitignore", {"source-writes": 23}],
  ["echo x > $HOME/a.py", {"source-writes": 24}],
  ["ls src/*.ts", {}],
  ["cat a.ts | grep foo", {}],
  ["cat <<EOF > a.md\nhello\nEOF", {"source-writes": 8}],
  ["echo hi\nsed -i 's/x/y/' b.py", {"source-writes": 25}],
  ["sed -i \\\n  's/x/y/' b.py", {"source-writes": 25}],
  ["rsync -a src/ dest/ x.py", {"source-writes": 26}],
  ["install -m644 a.conf b.sh", {"source-writes": 27}],
  ["jq . a.json > /tmp/b.json", {}],
  ["jq . a.json > b.json", {"source-writes": 9}],
  ["x=1; echo $x > out.txt", {}],
  ["for f in src/*.ts; do sed -i 's/a/b/' $f; done", {}],
  ["echo done > /dev/null && cp x.md y.md", {"source-writes": 28}],
  ["ed a.lua < script", {"source-writes": 29}],
  ["cp a.ts /tmp/a.ts; echo ok > b.ts", {"source-writes": 30}],
  ["cargo mutants", {"builds": 31}],
  ["cargo mutants --list", {}],
  ["cargo mutants --version", {}],
  ["cargo-mutants", {"builds": 31}],
  ["TMPDIR=/tmp cargo mutants", {"builds": 32}],
  ["TMPDIR=/tmp/x cargo mutants", {"builds": 32}],
  ["TMPDIR=~/.cache/m cargo mutants", {"builds": 33}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope cargo mutants", {"builds": 34}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope -p MemoryMax=3G cargo mutants", {"builds": 35}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope -p MemoryMax=3G nice -n 10 cargo mutants -j8", {}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope -p MemoryMax=3G nice -n 10 cargo mutants -j12", {"builds": 36}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope -p MemoryMax=3G nice -n 10 cargo mutants --jobs=9", {"builds": 37}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope -p MemoryMax=3G nice -n 10 cargo mutants -j 4", {}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope -p MemoryMax=3G nice -n 10 cargo mutants", {}],
  ["TMPDIR=~/.cache/m systemd-run --user --scope -p MemoryMax=3G nicer cargo mutants", {"builds": 35}],
  ["TMPDIR=~/.cache/m \\\n  systemd-run --user --scope -p MemoryMax=3G nice -n 10 cargo mutants -j8", {}],
  ["cargo build -j16", {}],
  ["echo cargo mutants", {"builds": 31}],
  ["until cargo mutants; do :; done > src/log.md", {"keywords": 0, "source-writes": 38, "builds": 31}],
]
